# Generated by Django 4.0.2 on 2022-03-30 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('desc', models.TextField(verbose_name='Description')),
                ('registration_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Start of registration')),
                ('registration_stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='Registration deadline')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last name')),
                ('email', models.CharField(max_length=200, verbose_name='E-Mail')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Moment of registration')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('registration_stopped_at__gt', django.db.models.expressions.F('registration_started_at'))), name='registration_period_valid'),
        ),
    ]
