# Generated by Django 4.0.2 on 2022-03-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_participant_email'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='unique_event_email_combination'),
        ),
    ]
