# Generated by Django 4.0.2 on 2022-04-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_participant_unique_event_email_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approval of registration'),
        ),
    ]
