# Generated by Django 4.1.1 on 2022-09-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_participant_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='mobile',
            field=models.CharField(max_length=20, null=True, verbose_name='Mobile number'),
        ),
    ]
