# Generated by Django 3.2.5 on 2021-11-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='group',
            field=models.CharField(choices=[
                ('job', 'Job'),
                ('thesis', 'Abschlussarbeit'),
                ('internship', 'Praktikum'),
                ('sideline', 'Nebentätigkeit')
            ], default='job', max_length=20),
            preserve_default=False,
        ),
    ]
