# Generated by Django 4.1 on 2022-10-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_remove_consultation_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['day', 'start'], 'verbose_name': 'Consultation', 'verbose_name_plural': 'Consultations'},
        ),
    ]
