# Generated by Django 4.0.2 on 2022-02-19 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=150)),
                ('lecturer', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('minute_author', models.EmailField(max_length=254, null=True)),
                ('minute_file', models.FileField(upload_to='exams/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
