# Generated by Django 4.0.2 on 2022-02-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_options_alter_exam_course_alter_exam_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
