# Generated by Django 3.1.4 on 2020-12-19 12:39

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201211_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=blog.models.generate_random_name)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
