# Generated by Django 3.1.4 on 2021-01-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='visible',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
