# Generated by Django 3.1.4 on 2021-06-09 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-position']},
        ),
    ]
