# Generated by Django 4.0.2 on 2022-02-17 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210621_2239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
