# Generated by Django 4.0.2 on 2022-02-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_delete_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Protocol',
        ),
    ]
