# Generated by Django 4.0.2 on 2022-02-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_delete_protocol'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
    ]
