# Generated by Django 4.1.6 on 2023-02-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_delete_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
