# Generated by Django 4.1.12 on 2024-01-20 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
