# Generated by Django 4.0.6 on 2022-07-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0003_alter_helper_created_at_alter_mentor_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('started_at', models.DateTimeField(verbose_name='Started at')),
                ('stopped_at', models.DateTimeField(verbose_name='Stopped at')),
                ('is_helper_form_active', models.BooleanField(default=False, verbose_name='Is helper form active?')),
                ('helper_form_desc', models.TextField(blank=True, verbose_name='Description text for helper form')),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
            },
        ),
    ]
