# Generated by Django 4.0.6 on 2022-07-19 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0005_helper_registration_mentor_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='helper_form_desc',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='is_helper_form_active',
        ),
        migrations.DeleteModel(
            name='Helper',
        ),
    ]
