# Generated by Django 4.0.6 on 2022-07-20 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentoring', '0006_remove_registration_helper_form_desc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Mentor', 'verbose_name_plural': 'Mentors'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name'], 'verbose_name': 'Study program', 'verbose_name_plural': 'Study programs'},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['name'], 'verbose_name': 'Registration', 'verbose_name_plural': 'Registrations'},
        ),
    ]
