# Generated by Django 4.1.9 on 2023-05-21 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Gruppe',
                'verbose_name_plural': 'Gruppen',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['title'], 'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumente'},
        ),
        migrations.AddField(
            model_name='document',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.group'),
        ),
    ]
