# Generated by Django 3.2.4 on 2021-09-14 21:17

from django.db import migrations, models
import django.db.models.deletion
import excursions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, verbose_name='description')),
                ('visit_on', models.DateTimeField()),
                ('seats', models.PositiveSmallIntegerField()),
                ('is_car_required', models.BooleanField(default=True)),
                ('registration_begins_at', models.DateTimeField(blank=True, null=True)),
                ('registration_ends_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, validators=[excursions.models.validate_university_email])),
                ('phone', models.CharField(max_length=16, validators=[excursions.models.validate_phone])),
                ('is_car_owner', models.BooleanField()),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excursions.excursion')),
            ],
        ),
    ]
