# Generated by Django 3.2.4 on 2021-09-18 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0002_rename_participants_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='visit_on',
            new_name='date',
        ),
        migrations.AddField(
            model_name='excursion',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excursion',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
