# Generated by Django 3.2.4 on 2021-09-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0003_auto_20210918_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='date',
            field=models.DateField(),
        ),
    ]
