# Generated by Django 5.1.2 on 2025-04-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('home', '0001_initial'), ('home', '0002_alter_team_image_alter_team_label_and_more'), ('home', '0003_alter_team_label')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Die Verwendung der Jahreszahl und/oder Semester bietet sich an.', max_length=100, verbose_name='Bezeichnung')),
                ('image', models.ImageField(help_text='Bild mit den aktuellen Mitgliedern', upload_to='teams/', verbose_name='Bild')),
                ('release_date', models.DateField(help_text='Datum der Veröffentlichung', unique=True, verbose_name='Freigabedatum')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
