# Generated by Django 5.1.2 on 2024-11-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(help_text='Bild mit den aktuellen Mitgliedern', upload_to='teams/', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='team',
            name='label',
            field=models.CharField(help_text='Die Verwendung der Jahreszahl und/oder Semester bietet sich an.', verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='team',
            name='release_date',
            field=models.DateField(help_text='Datum der Veröffentlichung', unique=True, verbose_name='Freigabedatum'),
        ),
    ]
