# Generated by Django 4.0.2 on 2022-02-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('position', models.PositiveSmallIntegerField(unique=True, verbose_name='Position')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['position'],
            },
        ),
    ]
