# Generated by Django 4.0.2 on 2022-02-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, unique=True, verbose_name='Position'),
        ),
    ]
