# Generated by Django 3.2.4 on 2021-08-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='semester',
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='course',
            field=models.CharField(choices=[('EMO', 'Elektromobilität'), ('IDE', 'Integrated Design Engineering'), ('MB', 'Maschinenbau'), ('MTK', 'Mechatronik'), ('SEM', 'Systems Engineering for Manufacturing'), ('WLO', 'Wirtschaftsingenieur Logistik'), ('WMB', 'Wirtschaftsingenieur Maschinenbau')], max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jobs',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='joined_at',
            field=models.DateField(),
        ),
    ]
