# Generated by Django 3.2.4 on 2021-09-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.CharField(choices=[('BSC', 'Bachelor of Science'), ('MSC', 'Master of Science')], default='BSC', max_length=3),
            preserve_default=False,
        ),
    ]
