# Generated by Django 4.1.13 on 2024-08-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_profile_course_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='degree',
            field=models.CharField(choices=[('BSC', 'Bachelor of Science'), ('MSC', 'Master of Science'), ('ABS', 'Alumnus')], max_length=3),
        ),
    ]
