# Generated by Django 5.1.2 on 2025-02-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_remove_user_relationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Member', 'verbose_name_plural': 'Members'},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='course',
            new_name='program',
        ),
        migrations.AlterField(
            model_name='member',
            name='program',
            field=models.CharField(choices=[('Bachelor', [('AI', 'AI Engineering'), ('EMO', 'E-Mobility'), ('ESC', 'Engineering Science'), ('MB-B', 'Mechanical Engineering (Bachelor)'), ('MECH-B', 'Mechatronics (Bachelor)'), ('WLO', 'Industrial Engineering for Logistics (Bachelor)'), ('WMB', 'Industrial Engineering for Mechanical Engineering (Bachelor)')]), ('Master', [('BE', 'Biomechanical Engineering'), ('CME', 'Computational Methods in Engineering'), ('IDE', 'Integrated Design Engineering'), ('MB-M', 'Mechanical Engineering (Master)'), ('MECH-M', 'Mechatronics (Master)'), ('SEM', 'Systems Engineering for Manufacturing'), ('WING', 'Industrial Engineering (Master)')])], default='', max_length=6, verbose_name='Program'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_at',
            field=models.DateField(verbose_name='Date of accession'),
        ),
    ]
