# Generated by Django 5.1.2 on 2025-02-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_member_options_remove_member_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_alumnus',
            field=models.BooleanField(default=False, help_text='Successfully completed his degree', verbose_name='Alumnus'),
        ),
        migrations.AddField(
            model_name='member',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Visibility'),
        ),
        migrations.RunSQL(
            sql="UPDATE members_member SET is_visible = TRUE",
            reverse_sql="UPDATE members_member SET is_visible = FALSE",
        ),
    ]
